"""Initial Migration

Revision ID: ffbecf4278fe
Revises:
Create Date: 2020-09-12 12:13:20.812549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbecf4278fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('high_risk', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('avg_period', sa.String(length=20), nullable=False),
    sa.Column('avg_cycle', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    op.drop_table('day')
    # ### end Alembic commands ###
